name: Deploy
run-name: Build du projet et dépot sur la prod
on: workflow_dispatch
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actions dans le SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd next-cda241/
            git pull origin master