name: CI Next.js
run-name: Build d'une appli et cache
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupère le code du repo
        uses: actions/checkout@v4
      - name: Mets en cache node_modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installe les dépendences
        run: npm install
      - name: Build l'application
        run: npm run build
  Test:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Récupère le code du repo
        uses: actions/checkout@v4
      - name: Restore node_modules cache
        uses: actions/cache/restore@v4
        with:
          path: |
            **/node_modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Installe le binaire de Cypress
        run: ./packages/core/node_modules/cypress/bin/cypress install
      - name: Run les tests
        run: npm run e2e